---
- name: Ensure homeassistant is up
  tags: homeassistant_docker
  community.docker.docker_container:
    name: home-assistant
    image: homeassistant/home-assistant:stable
    state: started
    privileged: true
    tty: true
    network_mode: host
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/homeassistant/config:/config
    pull: true
    restart_policy: unless-stopped
    env:
      TZ: America/New_York
