---
- hosts: frigate
  roles:
    - role: frigate_docker
      vars:
        # mqtt_host: "{{hostvars[groups['mosquitto'][0]].ansible_host }}"
        mqtt_host: homeassistant.home.arpa
        mqtt_user: frigate
