---
# ansible-playbook -i 10.0.1.222, --ask-pass --ask-become-pass zotac_docker.yml
- name: install base
  hosts: all
  remote_user: joe
  become: yes
  become_method: su
  become_flags: "-"

  vars:
    base_packages:
      - gpp
      - sudo
      - python3-pip
      - python3-apt

    authorized_key:
      key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAmKH3riQOx30KqVLYtffZ1st9ihcvQPys93KtWmUR7UI8u4PX3qLU28QjvjaRgyn+vYGi9KR14HmNxs0wEaho2u/ImESQEgZawWElyBIISKudWXD2+x3FolITxfiM4+fhGVN+UAymL81F6YBZsKs2TM8bRd33XkgUlcDpMyBWfBU=
      comment: joebelford@joe-belfords-computer.local

  tasks:
    - name: install base packages
      apt:
        name: "{{ base_packages }}"
        state: latest

    - name: add joe to sudoers
      ansible.builtin.user:
        name: joe
        groups:
          - sudo
        append: yes

    - name: add authorized key
      ansible.posix.authorized_key:
        user: joe
        key: "{{ authorized_key.key }}"
        comment: "{{ authorized_key.comment }}"

- name: install docker
  hosts: all
  remote_user: joe
  become: yes
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

  tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add docker apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present
        update_cache: yes

    - name: Install docker packages
      apt:
        name: "{{ docker_packages }}"
        state: latest
        update_cache: yes
      tags: docker_packages

    - name: Install docker python module
      pip:
        name: docker
        state: latest

- name: install video support
  hosts: all
  remote_user: joe
  become: yes
  vars:
    debian_repos:
      - deb http://deb.debian.org/debian bullseye main contrib non-free
      - deb-src http://deb.debian.org/debian bullseye main contrib non-free
      - deb http://deb.debian.org/debian-security bullseye-security main contrib non-free
      - deb-src http://deb.debian.org/debian-security bullseye-security main contrib non-free
      - deb http://deb.debian.org/debian bullseye-updates main contrib non-free
      - deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free

    hwaccel_packages:
      - mesa-va-drivers
      - vainfo

  tasks:
    - name: Add contrib and non-free repos
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ debian_repos }}"

    - name: Install hwaccel packages
      apt:
        name: "{{ hwaccel_packages }}"
        state: latest
        update_cache: yes
      tags: docker_packages
