---
- name: Ensure prometheus opt directory exists
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    mode: "0755"

- name: Ensure prometheus var directory exists
  ansible.builtin.file:
    path: /var/prometheus
    state: directory
    mode: "0755"
    owner: nobody
    group: nobody

- name: Deploy config file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml
    mode: "0644"
