---
- name: Enable zoneminder conf
  ansible.builtin.command: a2enconf zoneminder
  tags: apache

- name: Enable module
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ apache_modules }}"
  tags: apache

- name: Reload apache2 service
  ansible.builtin.systemd:
    name: apache2
    state: reloaded
  tags: apache
