---
- name: Configure date time in php.ini
  community.general.ini_file:
    path: /etc/php/7.3/apache2/php.ini
    section: Date
    option: date.timezone
    value: America/New_York
    backup: true
  tags: config
