---
- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian/ buster main contrib non-free
    state: present
    update_cache: true

- name: Update repositories cache and install "nvidia" package
  ansible.builtin.apt:
    name: nvidia-legacy-340xx-driver
    update_cache: true
