---
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://zmrepo.zoneminder.com/debian/archive-keyring.gpg
    state: present

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: deb https://zmrepo.zoneminder.com/debian/release-1.34 buster/
    state: present
    update_cache: true

- name: Add contrib and non-free apt repository
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian/ buster main contrib non-free
    state: present
    update_cache: true
