---
- name: Update repositories cache and install "zoneminder" package
  ansible.builtin.apt:
    name: zoneminder
    update_cache: true

- name: Add the user
  ansible.builtin.user:
    name: www-data
    comment: www-data user
    group: www-data
    groups:
      - video
      - render
    append: true
    state: present

- name: Enable zoneminder service
  ansible.builtin.systemd:
    name: zoneminder
    state: started
    enabled: true
