---
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - docker-compose
  - python3-pip # needed to install docker-python module for community.docker ansible collection
