---
- name: Ensure mosquitto directory exists
  ansible.builtin.file:
    path: /opt/mosquitto
    state: directory
    mode: "0750"
    owner: 1883
    group: 1883

- name: Ensure mosquitto log directory exists
  ansible.builtin.file:
    path: /opt/mosquitto/{{ item }}
    state: directory
    mode: "0750"
    owner: 1883
    group: 1883
  loop:
    - log
    - data
    - config

- name: Ensure config file
  ansible.builtin.copy:
    src: mosquitto.conf
    dest: /opt/mosquitto/config/mosquitto.conf
    mode: "0640"
    owner: 1883
    group: 1883
