---
- name: ensure mosquitto directory exists
  file:
    path: /opt/mosquitto
    state: directory
    mode: "0750"
    owner: 1883
    group: 1883

- name: ensure mosquitto log directory exists
  file:
    path: /opt/mosquitto/{{ item }}
    state: directory
    mode: "0750"
    owner: 1883
    group: 1883
  loop:
    - log
    - data
    - config

- name: ensure config file
  copy:
    src: mosquitto.conf
    dest: /opt/mosquitto/config/mosquitto.conf
    mode: "0640"
    owner: 1883
    group: 1883
