---
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=openhab
    state: present

- name: Add openhab apt repository
  ansible.builtin.apt_repository:
    repo: deb https://openhab.jfrog.io/openhab/openhab-linuxpkg testing main
    state: present
    update_cache: true
