---
- hosts: all
  vars:
    ansible_python_interpreter: /opt/local/bin/python
#  remote_user: admin
  become: yes
  become_method: sudo
  tasks:
  - name: update database 
    pkgin:
      update_cache: yes
