---
- name: Ensure unifi directories exists
  ansible.builtin.file:
    path: /opt/unifi/{{ item }}
    state: directory
    recurse: true
    mode: "0750"
    owner: 1000
    group: 1000
  loop:
    - config
    - data

- name: deploy init script
  ansible.builtin.template:
    src: init-mongo.js.j2
    dest: /opt/unifi/init-mongo.js
    mode: "0750"
    owner: 1000
    group: 1000
