
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
cloud:
lovelace:
  resources:
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
notify:
  - name: ALL_DEVICES
    platform: group
    services:
       - service: mobile_app_joe_s_iphone
       - service: mobile_app_kristys_iphone

