---
base_packages:
        - apache2
        - mariadb-server
        - php
        - libapache2-mod-php
        - php-mysql
        - apt-transport-https
        - gnupg

apache_modules:
        - rewrite
        - headers
        - expires
        - cgi
