---
- name: create router zone
  vmadm:
    brand: joyent
    state: running
    alias: router
    hostname: 'router'
    dns_domain: 'home.joe'
    autoboot: yes
#    image_uuid: 7b021460-73f9-11ea-a6da-07800cddb2ca
    image_uuid: 064508d4-73fa-11ea-84d8-b3f1f91c535e
    firewall_enabled: no
    max_physical_memory: 512
    nics:
      - nic_tag: external
        ip: dhcp
#        ips: [10.0.2.1/24]
        resolvers: [ 64.6.64.6, 64.6.65.6 ]
        allow_ip_spoofing: true
        interface: net0
        primary: true
      - nic_tag: internal
        ips: [10.0.1.2/24]
        allow_ip_spoofing: true
        allow_dhcp_spoofing: true
        dhcp_server: true
        interface: net1
      - nic_tag: guest
        ips: [172.16.42.1/24]
        allow_ip_spoofing: true
        allow_dhcp_spoofing: true
        dhcp_server: true
        interface: net2
        vland_id: 1003
    customer_metadata:
      'root_authorized_keys': "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfseBIh3jctvBxoZHut/hJHNgiYZOlkHcCZPl80/ihY6sgPXIiLk1D/ipaNECj40ZNLecznCYrR/442y30aPDODhs/IYw3bq4tQRANgBH/Nebi7WUovYuT9UuetqlOSBd21cEWygH24Xhe2y7VcMv0QfhxzxCMkIralQWI+2f7/OuLiUlowD+ckZSf+0ypRuvW2sqj2Yc13fSJY+nfPD/8XNT7hOJoaKxDLm8gy4RI+XN5foelyJmawTjQGSzuKsxpBzeKL30lI7ZBP5pwCK08q92fEBInIleMDikujthz0d3+NjNrPVoi0gijR1GyQFlz8DstfFONIMfd6asbrcmr joe@joe-desktop"
      'ansible_pubkey': "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAmKH3riQOx30KqVLYtffZ1st9ihcvQPys93KtWmUR7UI8u4PX3qLU28QjvjaRgyn+vYGi9KR14HmNxs0wEaho2u/ImESQEgZawWElyBIISKudWXD2+x3FolITxfiM4+fhGVN+UAymL81F6YBZsKs2TM8bRd33XkgUlcDpMyBWfBU= joebelford@joe-belfords-computer.local"
      'user-script': '/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys; /usr/sbin/mdata-get ansible_pubkey >> ~root/.ssh/authorized_keys'
    internal_metadata:
      root_pw: ''
    quota: 20

