---
- name: Add authorized key
  ansible.posix.authorized_key:
    user: joe
    key: "{{ lookup('file', item) }}" # noqa jinja[spacing]
  with_fileglob:
    - "*.pub"

- name: Configure grub for serial terminal
  when: ansible_chassis_vendor == 'HPE'
  tags: grub
  notify: Execute grub-mkconfig
  block:
    - name: Set GRUB_CMDLINE_LINUX
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        state: present
        regexp: ^\#*(GRUB_CMDLINE_LINUX=).*$
        line: \1"console=ttyS0,115200n8"
        backrefs: true

    - name: Set GRUB_TERMINAL
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        state: present
        regexp: ^\#*(GRUB_TERMINAL=)(.*)$
        line: \1"serial \2"
        backrefs: true

    - name: Set GRUB_SERIAL_COMMAND
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        state: present
        backrefs: false # can't use backrefs because line doesn't exist
        regexp: ^\#*GRUB_SERIAL_COMMAND=.*
        line: GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
