---
- name: Add contrib and non-free repos
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ debian_repos }}"

- name: install base packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: latest

- name: install dev packages
  ansible.builtin.apt:
    name: "{{ dev_packages }}"
    state: latest
  tags:
    - dev

- name: Install vainfo package
  ansible.builtin.apt:
    name: vainfo
    state: latest
    update_cache: true

- name: Install mesa-va-drivers package
  ansible.builtin.apt:
    name: mesa-va-drivers
    state: latest
    update_cache: true
  when: inventory_hostname_short == 'zotac'

- name: Install intel-media-va-driver-non-free package
  ansible.builtin.apt:
    name: intel-media-va-driver-non-free
    state: latest
    update_cache: true
  when: inventory_hostname_short == 'proliant'

- name: add joe to sudoers
  ansible.builtin.user:
    name: joe
    groups:
      - sudo
      - adm
      - render
    append: true

- name: no password for sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: ^%sudo
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s

- name: Add authorized key
  ansible.posix.authorized_key:
    user: joe
    key: "{{ lookup('file', item) }}" # noqa jinja[spacing]
  with_fileglob:
    - "*.pub"

- name: Configure grub for serial terminal
  when: inventory_hostname_short == 'proliant'
  tags: grub
  notify: execute grub-mkconfig
  block:
    - name: Set GRUB_CMDLINE_LINUX
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        state: present
        regexp: ^GRUB_CMDLINE_LINUX="console=ttyS0,115200n8"$
        line: GRUB_CMDLINE_LINUX="console=ttyS0,115200n8"

    - name: Set GRUB_TERMINAL
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        state: present
        regexp: ^GRUB_TERMINAL=.*
        line: GRUB_TERMINAL="serial console"

    - name: Set GRUB_SERIAL_COMMAND
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        state: present
        regexp: ^GRUB_SERIAL_COMMAND=.*
        line: GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
