---
- name: Install packages
  community.general.pkgin:
    name: dnsmasq
    update_cache: false

- name: Apply /opt/local/etc/dnsmasq.conf
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /opt/local/etc/dnsmasq.conf
    owner: root
    group: root
    mode: "0644"

- name: Create /var/cache direcetory
  ansible.builtin.file:
    path: /var/cache
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Enable dnsmasq service
  ansible.builtin.service:
    name: dnsmasq
    enabled: true
    state: started
