---
- name: Deploy /etc/ipf/ipnat.conf file
  ansible.builtin.copy:
    src: ipnat.conf
    dest: /etc/ipf/ipnat.conf
    owner: root
    group: sys
    mode: "0644"

- name: Configure routing
  ansible.builtin.command: routeadm -u -e ipv4-forwarding
- name: Enable ipfilter service
  ansible.builtin.service:
    name: ipfilter
    enabled: true
    state: started
