---
- name: deploy /etc/ipf/ipnat.conf file
  copy:
    src: ipnat.conf
    dest: /etc/ipf/ipnat.conf
    owner: root
    group: sys
    mode: "0644"

- name: configure routing
  command: "routeadm -u -e ipv4-forwarding"

- name: enable ipfilter service
  service:
    name: ipfilter
    enabled: yes
    state: started
