---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present
    update_cache: yes

- name: Install docker packages
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: yes

- name: Install docker python module
  pip:
    name: docker
    state: latest