---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: present
    update_cache: true
- name: Install docker packages
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: true

- name: Install docker python module
  pip:
    name: docker
    state: latest

- name: add joe to docker group
  ansible.builtin.user:
    name: joe
    groups:
      - docker
    append: true
