---
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: present
    update_cache: true

- name: Install docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: true

# - name: Install docker python module
#   ansible.builtin.pip:
#     name: docker
#     state: latest

- name: Add joe to docker group
  ansible.builtin.user:
    name: joe
    groups:
      - docker
    append: true
