---
- name: Update repositories cache and install "zoneminder" package
  apt:
    name: zoneminder
    update_cache: yes
    state: absent

- name: Add the user 
  user:
    name: www-data
    comment: www-data user
    group: www-data
    groups: 
        - video
        - render
    append: yes
    state: absent

