---
base_packages:
  - gpp
  - sudo
  - python3-pip
  - python3-apt
  - firmware-linux-nonfree
  - avahi-daemon
  - cifs-utils
  - zip
  - net-tools

dev_packages:
  - libavahi-compat-libdnssd-dev
  # - clang
  - ffmpeg
  - libavformat-dev
  - libavcodec-dev
  - libavutil-dev
  # - gdb
  # - git
  - libavahi-compat-libdnssd-dev
  - libssl-dev
  - make
  # - openssh-server
  # - perl
  # - unzip
  # - wget

debian_repos:
  - deb http://deb.debian.org/debian bullseye main contrib non-free
  - deb-src http://deb.debian.org/debian bullseye main contrib non-free
  - deb http://deb.debian.org/debian-security bullseye-security main contrib non-free
  - deb-src http://deb.debian.org/debian-security bullseye-security main contrib non-free
  - deb http://deb.debian.org/debian bullseye-updates main contrib non-free
  - deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free
