---
- name: Ensure docker image available
  containers.podman.podman_image:
    name: "{{ frigate_image }}"
    source: pull

- name: Ensure frigate is up
  containers.podman.podman_container:
    name: frigate
    image: "{{ frigate_image }}"
    state: started
    tty: true
    devices:
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config.yml:/config/config.yml:ro
      - /media/frigate:/media/frigate:z
    shm_size: 64M
    privileged: true
    restart: true
    ports:
      - 5000:5000
      - 1935:1935
      - 8554:8554
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    pull: true
    restart_policy: unless-stopped
    env:
      TZ: America/New_York
      FRIGATE_RTSP_PASSWORD: "{{ FRIGATE_RTSP_PASSWORD }}"
      # LIBVA_DRIVER_NAME: i965 # Not needed
      DEBIAN_FRONTEND: noninteractive
      FRIGATE_MQTT_USER: "{{ mqtt_user }}"
      FRIGATE_MQTT_PASSWORD: "{{ mqtt_user }}"
